name: CI

on:
  # push:
  #   branches:
  #     - "*"
  workflow_dispatch:
    inputs: 
      env:
        description: "Env to build"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "CI is running" 
