name: CI

on:
  # push:
  #   branches:
  #     - "*"
  workflow_dispatch:
    inputs: 
      env:
        description: "Env to build"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
      deploy:
        description: "Deploy to env"
        required: true
        default: "false"
        type: boolean
      note:
        description: "Note to build"
        required: false
        default: ""
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "CI is running" 
